spring:
  application:
    name: VoyageHub

  datasource:
    url: jdbc:postgresql://localhost:5432/bus
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

    security:
      user:
        name: user
        password: 123